name: pro

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title'
        required: true
        type: string
        default: '变更说明'
      name:
        description: 'Name'
        required: true
        type: choice
        options:
          - aigcpanel
          - focusany
          - linkandroid
      os:
        description: 'OS'
        required: true
        type: choice
        default: windows-latest
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      arch:
        description: 'Arch'
        required: true
        type: choice
        default: amd64
        options:
          - amd64
          - arm64
      uploadType:
        description: 'Upload Type'
        required: true
        type: choice
        default: AliyunOss
        options:
          - None
          - QiniuKodo
          - AliyunOss

run-name: ${{ github.event.inputs.name }}|${{ github.event.inputs.os }}|${{ github.event.inputs.arch }}

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ${{ github.event.inputs.os }}
            arch: ${{ github.event.inputs.arch }}

    steps:

      - name: RunInfo
        run: |
          echo "Arch: ${{ runner.os }} - ${{ runner.arch }}"
          echo "Name: ${{ github.event.inputs.name }}"
          echo "UploadType: ${{ github.event.inputs.uploadType }}"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Git clone repo
        if: runner.os == 'Linux' || runner.os == 'macOS'
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_REPO_BASE: ${{ secrets.GIT_REPO_BASE }}
          GIT_HOST: ${{ secrets.GIT_HOST }}
          COMMON_NAME: ${{ github.event.inputs.name }}
        run: |
          git clone "https://${GIT_USER}:${GIT_PASS}@${GIT_HOST}/${GIT_REPO_BASE}/${COMMON_NAME}-pro.git" code

      - name: Git clone repo
        if: runner.os == 'Windows'
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_PASS: ${{ secrets.GIT_PASS }}
          GIT_REPO_BASE: ${{ secrets.GIT_REPO_BASE }}
          GIT_HOST: ${{ secrets.GIT_HOST }}
          COMMON_NAME: ${{ github.event.inputs.name }}
        shell: pwsh
        run: |
          git clone "https://${env:GIT_USER}:${env:GIT_PASS}@${env:GIT_HOST}/${env:GIT_REPO_BASE}/${env:COMMON_NAME}-pro.git" code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Prepare (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install libxtst-dev libpng++-dev

      - name: Build Prepare (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install python-setuptools


      - name: Cert Prepare (macOS)
        if: runner.os == 'macOS'
        env:
          MACOS_CERTIFICATE: ${{ secrets.CORP_MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.CORP_MACOS_CERTIFICATE_PASSWORD }}
        run: |
          echo "find-identity"
          security find-identity -p codesigning
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "" build.keychain
          echo "find-identity"
          security find-identity -v -p codesigning build.keychain
          echo "find-identity"
          security find-identity -p codesigning
          echo "set-key-partition-list"
          security set-key-partition-list -S apple-tool:,apple: -s -k "" -l "Mac Developer ID Application: Xi'an Yanyi Information Technology Co., Ltd" -t private build.keychain
          echo "export"
          security export -k build.keychain -t certs -f x509 -p -o certificate.cer
          echo "add-trusted-cert"
          sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain certificate.cer
          echo "find-identity"
          security find-identity -p codesigning

      - name: Install Dependencies
        working-directory: code
        run: npm install

      - name: Build Release Files
        working-directory: code
        run: |
            npm run build
        env:
          DEBUG: "electron-notarize:*"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Set Build Name ( Linux / macOS )
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          DIST_FILE_NAME=${{ runner.os }}-${{ runner.arch }}-v$(date +%Y%m%d_%H%M%S)-${RANDOM}
          echo ::add-mask::$DIST_FILE_NAME
          echo DIST_FILE_NAME=$DIST_FILE_NAME >> $GITHUB_ENV

      - name: Set Build Name ( Windows )
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $randomNumber = Get-Random -Minimum 10000 -Maximum 99999
          $DIST_FILE_NAME = "Windows-X64-v$(Get-Date -Format 'yyyyMMdd_HHmmss')-$randomNumber"
          Write-Host "::add-mask::$DIST_FILE_NAME"
          echo "DIST_FILE_NAME=$DIST_FILE_NAME" >> $env:GITHUB_ENV

      - name: Upload Kodo
        if: github.event.inputs.uploadType == 'QiniuKodo'
        uses: modstart/github-kodo-action@master
        env:
          COMMON_NAME: ${{ github.event.inputs.name }}
        with:
          title: ${{ github.event.head_commit.message }}
          accessKey: ${{ secrets.KODO_ACCESS_KEY }}
          secretKey: ${{ secrets.KODO_SECRET_KEY }}
          bucket: ${{ secrets.KODO_BUCKET }}
          domain: ${{ secrets.KODO_DOMAIN }}
          zone: ${{ secrets.KODO_ZONE }}
          callback: ${{ secrets.OSS_CALLBACK }}
          assets: |
            code/dist-release/*.exe:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.dmg:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.AppImage:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.deb:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/

      - name: Upload Oss
        if: github.event.inputs.uploadType == 'AliyunOss'
        uses: modstart/github-oss-action@master
        env:
          COMMON_NAME: ${{ github.event.inputs.name }}
        with:
          title: ${{ github.event.inputs.title }}
          key-id: ${{ secrets.OSS_2_KEY_ID }}
          key-secret: ${{ secrets.OSS_2_KEY_SECRET }}
          region: ${{ secrets.OSS_2_REGION }}
          bucket: ${{ secrets.OSS_2_BUCKET }}
          callbackUrlSign: ${{ secrets.OSS_2_CALLBACK_URL_SIGN }}
          callback: ${{ secrets.OSS_2_CALLBACK }}
          assets: |
            code/dist-release/*.exe:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.dmg:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.AppImage:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
            code/dist-release/*.deb:apps/${{ env.COMMON_NAME }}pro-${{ env.DIST_FILE_NAME }}/
